CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN
  CREATE TYPE role AS ENUM ('admin', 'developer', 'readonly');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE job_state AS ENUM ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'expired');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE crawl_state AS ENUM ('queued', 'running', 'succeeded', 'failed', 'cancelled');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS api_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  role role NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS api_tokens_project_idx ON api_tokens(project_id);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  key VARCHAR(128) NOT NULL,
  request_hash TEXT NOT NULL,
  job_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(project_id, key)
);

CREATE TABLE IF NOT EXISTS jobs (
  id UUID PRIMARY KEY,
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  state job_state NOT NULL DEFAULT 'queued',
  url TEXT NOT NULL,
  request_json JSONB NOT NULL,
  result_summary JSONB,
  error_message TEXT,
  request_id VARCHAR(128) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3,
  cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS jobs_project_state_idx ON jobs(project_id, state);
CREATE INDEX IF NOT EXISTS jobs_request_id_idx ON jobs(request_id);

CREATE TABLE IF NOT EXISTS job_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  level VARCHAR(16) NOT NULL,
  message TEXT NOT NULL,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS job_logs_job_idx ON job_logs(job_id);

CREATE TABLE IF NOT EXISTS artifact_blobs (
  sha256 VARCHAR(64) PRIMARY KEY,
  storage_key TEXT NOT NULL UNIQUE,
  content_type VARCHAR(128) NOT NULL,
  byte_size INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS artifacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID REFERENCES jobs(id) ON DELETE SET NULL,
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  type VARCHAR(64) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  blob_sha256 VARCHAR(64) NOT NULL REFERENCES artifact_blobs(sha256) ON DELETE RESTRICT,
  byte_size INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS artifacts_project_idx ON artifacts(project_id);
CREATE INDEX IF NOT EXISTS artifacts_job_idx ON artifacts(job_id);

CREATE TABLE IF NOT EXISTS artifact_download_tokens (
  token UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artifact_id UUID NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS artifact_download_tokens_artifact_idx ON artifact_download_tokens(artifact_id);
CREATE INDEX IF NOT EXISTS artifact_download_tokens_project_idx ON artifact_download_tokens(project_id);

CREATE TABLE IF NOT EXISTS recipes (
  id VARCHAR(128) PRIMARY KEY,
  project_id VARCHAR(255) REFERENCES projects(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  version VARCHAR(64) NOT NULL,
  description TEXT,
  match JSONB NOT NULL,
  requires_browser BOOLEAN NOT NULL DEFAULT FALSE,
  steps JSONB,
  extraction JSONB,
  throttling JSONB,
  plugin_path TEXT,
  source VARCHAR(32) NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS crawl_runs (
  id UUID PRIMARY KEY,
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  seed TEXT NOT NULL,
  state crawl_state NOT NULL DEFAULT 'queued',
  rules JSONB NOT NULL,
  stats JSONB NOT NULL DEFAULT '{"queued":0,"running":0,"succeeded":0,"failed":0}'::jsonb,
  request_id VARCHAR(128) NOT NULL,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS crawl_runs_project_idx ON crawl_runs(project_id);

CREATE TABLE IF NOT EXISTS crawl_nodes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  crawl_id UUID NOT NULL REFERENCES crawl_runs(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  parent_url TEXT,
  depth INTEGER NOT NULL,
  job_id UUID REFERENCES jobs(id) ON DELETE SET NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS crawl_nodes_crawl_depth_idx ON crawl_nodes(crawl_id, depth);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id VARCHAR(255) NOT NULL,
  token_id UUID,
  actor_role role NOT NULL,
  action VARCHAR(128) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id TEXT NOT NULL,
  request_id VARCHAR(128) NOT NULL,
  ip_address VARCHAR(64),
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS audit_logs_project_idx ON audit_logs(project_id);
CREATE INDEX IF NOT EXISTS audit_logs_action_idx ON audit_logs(action);

CREATE TABLE IF NOT EXISTS browser_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id VARCHAR(255) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  encrypted_cookies TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
